version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR
  build:
    commands:
      - echo Build started
      - docker build -t website .
  post_build:
    commands:
      - echo Build completed
